# Bind the canned view clusterrole to group sso-developers
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sso-developers-view
  namespace: dev
subjects:
- kind: Group
  name: sso-developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
# Bind the "developer" clusterrole to gain additional access
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sso-developers-developer
  namespace: dev
subjects:
- kind: Group
  name: sso-developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: developer
  apiGroup: rbac.authorization.k8s.io

